compile :
	gcc t09_01.c academic.c -o t09_01
	gcc t09_02.c academic.c -o t09_02
	gcc t09_03.c academic.c -o t09_03
	gcc t09_04.c academic.c -o t09_04

test_01 :
	./t09_01

test_02 :
	./t09_02

test_03 :
	./t09_03

test_04 :
	./t09_04

test_05 :
	./t09_04
